version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: restaurant-nginx
    ports:
      - 8000:80
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - mariadb
    networks:
      - restaurant-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-php
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - restaurant-network

  mariadb:
    image: mariadb:10.5.5
    container_name: restaurant-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=restaurant
      - MYSQL_PASSWORD=restaurant
      - MYSQL_DATABASE=restaurant_docker_laravel
    networks:
      - restaurant-network
  
  redis:
    image: redis:alpine
    container_name: restaurant-redis
    volumes:
      - ./docker/redis/:/data
    ports:
      - 6379:6379
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  restaurant-volume:
    driver: local